In [1]:
import torch

In [2]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

In [5]:
# scalar . 하나의 값.
scalar = torch.tensor([1.])
scalar2 = torch.tensor([3.])
scalar+scalar2


tensor([4.])

In [6]:
#vector . 2개이상 수치
vector1 = torch.tensor([1.,2.,3.])
vector2 = torch.tensor([4.,5.,6.])

torch.dot(vector1,vector2)


tensor(32.)

In [7]:
#행렬 : 2개이상의 벡터로 구성된 값.
matrix1 = torch.tensor([[1.,2.],[3.,4.]])
matrix2 = torch.tensor([[1.,2.],[3.,4.]])

torch.matmul(matrix1,matrix2)


tensor([[ 7., 10.],
        [15., 22.]])

In [10]:
#텐서: 여러 행렬로 구성된 것. 2차원 이상의 배열
tensor1= torch.tensor([
    [[1.,2.],
     [3.,4.]],
    
    [[5.,6.],
     [7.,8.]],
    
])

tensor2= torch.tensor([
    [[1.,2.],
     [3.,4.]],
    
    [[5.,6.],
     [7.,8.]],
    
])


tensor1-tensor2
torch.matmul(tensor1,tensor2)#각 위치의 행렬마다 시행.


tensor([[[  7.,  10.],
         [ 15.,  22.]],

        [[ 67.,  78.],
         [ 91., 106.]]])