## 로지스틱 회귀분석

코드를 이해하기 위한 예제

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

print('Using Pytorch version : ',torch.__version__,' Device : ',DEVICE)

Using Pytorch version :  1.10.0  Device :  cuda


In [3]:
torch.manual_seed(1)
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
#훈련 데이터 선언
print(x_train.shape)
print(y_train.shape)

#XW 결과 Y가 되려면. W:2x1 백터여야한다.

torch.Size([6, 2])
torch.Size([6, 1])


In [6]:
W = torch.zeros((2, 1), requires_grad=True) # 크기는 2 x 1
b = torch.zeros(1, requires_grad=True)

In [7]:
#가설 세우고 확인
#W=0 일때
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)


In [8]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)


In [9]:
#.binary_cross_entropy(예측값, 실제값)
#로지스틱 회귀 비용함수를 cross_entropy라고 한다.
#cost function. loss를 구한것.
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

In [10]:
#전체 과정

W = torch.zeros((2, 1), requires_grad=True) # 크기는 2 x 1
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)#여기서 W와 b를 계산 해야한다!

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()

    # cost로 H(x) 계산
    optimizer.zero_grad() #zero_grad는 gradient를 매 epoch마다 0으로 초기화
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


In [11]:
print(W,b)
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[3.2530],
        [1.5179]], requires_grad=True) tensor([-14.4819], requires_grad=True)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


In [4]:
#Weight에 절대값을 주는 방법
#Shifted weighted
#이떄는 학습이 안된다.


W = torch.randn((2, 1), requires_grad=True) # 크기는 2 x 1
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)#여기서 W와 b를 계산 해야한다!

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = ·(x_train.matmul(torch.abs(W)) + b)
    print(hypothesis)
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()
    
    # cost로 H(x) 계산
    optimizer.zero_grad() #zero_grad는 gradient를 매 epoch마다 0으로 초기화
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

tensor([[0.7677],
        [0.8932],
        [0.9047],
        [0.9691],
        [0.9838],
        [0.9890]], grad_fn=<SigmoidBackward0>)
Epoch    0/1000 Cost: 1.017644
tensor([[0.7052],
        [0.8324],
        [0.6584],
        [0.8750],
        [0.8926],
        [0.8494]], grad_fn=<SigmoidBackward0>)
tensor([[0.3965],
        [0.4613],
        [0.5007],
        [0.5752],
        [0.6300],
        [0.6739]], grad_fn=<SigmoidBackward0>)
tensor([[0.5268],
        [0.7067],
        [0.7966],
        [0.9031],
        [0.9483],
        [0.9704]], grad_fn=<SigmoidBackward0>)
tensor([[0.4971],
        [0.6371],
        [0.4232],
        [0.6785],
        [0.6983],
        [0.6104]], grad_fn=<SigmoidBackward0>)
tensor([[0.5048],
        [0.6961],
        [0.6299],
        [0.8469],
        [0.8958],
        [0.9023]], grad_fn=<SigmoidBackward0>)
tensor([[0.2448],
        [0.2810],
        [0.2640],
        [0.3215],
        [0.3428],
        [0.3440]], grad_fn=<SigmoidBackward0>)
tensor([[0

tensor([[0.0061],
        [0.0974],
        [0.1445],
        [0.8687],
        [0.9811],
        [0.9945]], grad_fn=<SigmoidBackward0>)
tensor([[0.0061],
        [0.0971],
        [0.1440],
        [0.8691],
        [0.9812],
        [0.9946]], grad_fn=<SigmoidBackward0>)
tensor([[0.0060],
        [0.0968],
        [0.1435],
        [0.8694],
        [0.9813],
        [0.9946]], grad_fn=<SigmoidBackward0>)
tensor([[0.0060],
        [0.0966],
        [0.1430],
        [0.8698],
        [0.9814],
        [0.9946]], grad_fn=<SigmoidBackward0>)
tensor([[0.0059],
        [0.0963],
        [0.1425],
        [0.8701],
        [0.9815],
        [0.9947]], grad_fn=<SigmoidBackward0>)
tensor([[0.0059],
        [0.0961],
        [0.1420],
        [0.8705],
        [0.9816],
        [0.9947]], grad_fn=<SigmoidBackward0>)
tensor([[0.0058],
        [0.0958],
        [0.1415],
        [0.8708],
        [0.9817],
        [0.9947]], grad_fn=<SigmoidBackward0>)
tensor([[0.0058],
        [0.0955],
     

tensor([[0.0010],
        [0.0513],
        [0.0663],
        [0.9298],
        [0.9952],
        [0.9989]], grad_fn=<SigmoidBackward0>)
tensor([[9.9591e-04],
        [5.1205e-02],
        [6.6186e-02],
        [9.2985e-01],
        [9.9521e-01],
        [9.9894e-01]], grad_fn=<SigmoidBackward0>)
tensor([[9.9208e-04],
        [5.1132e-02],
        [6.6080e-02],
        [9.2994e-01],
        [9.9522e-01],
        [9.9894e-01]], grad_fn=<SigmoidBackward0>)
tensor([[9.8828e-04],
        [5.1060e-02],
        [6.5974e-02],
        [9.3004e-01],
        [9.9524e-01],
        [9.9895e-01]], grad_fn=<SigmoidBackward0>)
tensor([[9.8450e-04],
        [5.0987e-02],
        [6.5868e-02],
        [9.3014e-01],
        [9.9525e-01],
        [9.9895e-01]], grad_fn=<SigmoidBackward0>)
tensor([[9.8074e-04],
        [5.0915e-02],
        [6.5763e-02],
        [9.3023e-01],
        [9.9527e-01],
        [9.9896e-01]], grad_fn=<SigmoidBackward0>)
tensor([[9.7699e-04],
        [5.0843e-02],
        [6.565

tensor([[3.5016e-04],
        [3.4589e-02],
        [4.2937e-02],
        [9.5218e-01],
        [9.9787e-01],
        [9.9961e-01]], grad_fn=<SigmoidBackward0>)
tensor([[3.4928e-04],
        [3.4556e-02],
        [4.2893e-02],
        [9.5222e-01],
        [9.9788e-01],
        [9.9961e-01]], grad_fn=<SigmoidBackward0>)
tensor([[3.4840e-04],
        [3.4522e-02],
        [4.2849e-02],
        [9.5227e-01],
        [9.9788e-01],
        [9.9961e-01]], grad_fn=<SigmoidBackward0>)
tensor([[3.4753e-04],
        [3.4489e-02],
        [4.2805e-02],
        [9.5231e-01],
        [9.9789e-01],
        [9.9961e-01]], grad_fn=<SigmoidBackward0>)
tensor([[3.4666e-04],
        [3.4456e-02],
        [4.2760e-02],
        [9.5235e-01],
        [9.9789e-01],
        [9.9961e-01]], grad_fn=<SigmoidBackward0>)
tensor([[3.4579e-04],
        [3.4424e-02],
        [4.2716e-02],
        [9.5240e-01],
        [9.9789e-01],
        [9.9961e-01]], grad_fn=<SigmoidBackward0>)
tensor([[3.4492e-04],
        [3.4

In [5]:
print(W,b)
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[3.2715],
        [1.5279]], requires_grad=True) tensor([-14.5674], requires_grad=True)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])
