## 로지스틱 회귀분석

코드를 이해하기 위한 예제

In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchsummary

if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

print('Using Pytorch version : ',torch.__version__,' Device : ',DEVICE)

Using Pytorch version :  1.9.0  Device :  cuda


In [4]:
torch.manual_seed(1)
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
#훈련 데이터 선언
print(x_train.shape)
print(y_train.shape)

#XW 결과 Y가 되려면. W:2x1 백터여야한다.

torch.Size([6, 2])
torch.Size([6, 1])


In [12]:
W = torch.zeros((2, 1), requires_grad=True) # 크기는 2 x 1
b = torch.zeros(1, requires_grad=True)

In [13]:
#가설 세우고 확인
#W=0 일때
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)


In [14]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)


In [15]:
#.binary_cross_entropy(예측값, 실제값)
#로지스틱 회귀 비용함수를 cross_entropy라고 한다.
#cost function. loss를 구한것.
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [16]:
#전체 과정

W = torch.zeros((2, 1), requires_grad=True) # 크기는 2 x 1
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)#여기서 W와 b를 계산 해야한다!

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()

    # cost로 H(x) 계산
    optimizer.zero_grad() #zero_grad는 gradient를 매 epoch마다 0으로 초기화
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


In [18]:
print(W,b)
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[3.2530],
        [1.5179]], requires_grad=True) tensor([-14.4819], requires_grad=True)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


In [26]:
#Weight에 절대값을 주는 방법
#Shifted weighted
#이떄는 학습이 안된다.


W = torch.zeros((2, 1), requires_grad=True) # 크기는 2 x 1
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)#여기서 W와 b를 계산 해야한다!

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(torch.abs(W)) + b)
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()
    
    # cost로 H(x) 계산
    optimizer.zero_grad() #zero_grad는 gradient를 매 epoch마다 0으로 초기화
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

0.6931471824645996
Epoch    0/1000 Cost: 0.693147
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996


0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
Epoch  500/1000 Cost: 0.693147
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996
0.6931471824645996


In [20]:
print(W,b)
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[0.],
        [0.]], requires_grad=True) tensor([0.], requires_grad=True)
tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True]])
