## 로지스틱 회귀분석

코드를 이해하기 위한 예제

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

print('Using Pytorch version : ',torch.__version__,' Device : ',DEVICE)

Using Pytorch version :  1.9.0  Device :  cuda


In [3]:
torch.manual_seed(1)
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
#훈련 데이터 선언
print(x_train.shape)
print(y_train.shape)

#XW 결과 Y가 되려면. W:2x1 백터여야한다.

torch.Size([6, 2])
torch.Size([6, 1])


In [6]:
W = torch.zeros((2, 1), requires_grad=True) # 크기는 2 x 1
b = torch.zeros(1, requires_grad=True)

In [7]:
#가설 세우고 확인
#W=0 일때
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)


In [8]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)


In [9]:
#.binary_cross_entropy(예측값, 실제값)
#로지스틱 회귀 비용함수를 cross_entropy라고 한다.
#cost function. loss를 구한것.
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

In [10]:
#전체 과정

W = torch.zeros((2, 1), requires_grad=True) # 크기는 2 x 1
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)#여기서 W와 b를 계산 해야한다!

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()

    # cost로 H(x) 계산
    optimizer.zero_grad() #zero_grad는 gradient를 매 epoch마다 0으로 초기화
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


In [11]:
print(W,b)
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[3.2530],
        [1.5179]], requires_grad=True) tensor([-14.4819], requires_grad=True)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


In [4]:
#Weight에 절대값을 주는 방법
#Shifted weighted
#이떄는 학습이 안된다.


W = torch.randn((2, 1), requires_grad=True) # 크기는 2 x 1
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)#여기서 W와 b를 계산 해야한다!

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(torch.abs(W)) + b)
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()
    print(cost)
    # cost로 H(x) 계산
    optimizer.zero_grad() #zero_grad는 gradient를 매 epoch마다 0으로 초기화
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

tensor(1.0176, grad_fn=<NegBackward>)
Epoch    0/1000 Cost: 1.017644
tensor(0.7487, grad_fn=<NegBackward>)
tensor(0.5380, grad_fn=<NegBackward>)
tensor(0.6254, grad_fn=<NegBackward>)
tensor(0.5820, grad_fn=<NegBackward>)
tensor(0.5445, grad_fn=<NegBackward>)
tensor(0.6983, grad_fn=<NegBackward>)
tensor(1.6294, grad_fn=<NegBackward>)
tensor(0.4140, grad_fn=<NegBackward>)
tensor(0.4230, grad_fn=<NegBackward>)
tensor(0.6211, grad_fn=<NegBackward>)
tensor(0.4268, grad_fn=<NegBackward>)
tensor(0.5390, grad_fn=<NegBackward>)
tensor(0.6895, grad_fn=<NegBackward>)
tensor(1.6801, grad_fn=<NegBackward>)
tensor(0.3026, grad_fn=<NegBackward>)
tensor(0.2972, grad_fn=<NegBackward>)
tensor(0.2939, grad_fn=<NegBackward>)
tensor(0.2886, grad_fn=<NegBackward>)
tensor(0.2893, grad_fn=<NegBackward>)
tensor(0.2874, grad_fn=<NegBackward>)
tensor(0.3129, grad_fn=<NegBackward>)
tensor(0.3028, grad_fn=<NegBackward>)
tensor(0.3945, grad_fn=<NegBackward>)
tensor(0.3541, grad_fn=<NegBackward>)
tensor(0.6142, grad

tensor(0.0596, grad_fn=<NegBackward>)
tensor(0.0594, grad_fn=<NegBackward>)
tensor(0.0593, grad_fn=<NegBackward>)
tensor(0.0591, grad_fn=<NegBackward>)
tensor(0.0589, grad_fn=<NegBackward>)
tensor(0.0588, grad_fn=<NegBackward>)
tensor(0.0586, grad_fn=<NegBackward>)
tensor(0.0584, grad_fn=<NegBackward>)
tensor(0.0583, grad_fn=<NegBackward>)
tensor(0.0581, grad_fn=<NegBackward>)
tensor(0.0579, grad_fn=<NegBackward>)
tensor(0.0578, grad_fn=<NegBackward>)
tensor(0.0576, grad_fn=<NegBackward>)
tensor(0.0575, grad_fn=<NegBackward>)
tensor(0.0573, grad_fn=<NegBackward>)
tensor(0.0571, grad_fn=<NegBackward>)
tensor(0.0570, grad_fn=<NegBackward>)
tensor(0.0568, grad_fn=<NegBackward>)
tensor(0.0567, grad_fn=<NegBackward>)
tensor(0.0565, grad_fn=<NegBackward>)
tensor(0.0564, grad_fn=<NegBackward>)
tensor(0.0562, grad_fn=<NegBackward>)
tensor(0.0561, grad_fn=<NegBackward>)
tensor(0.0559, grad_fn=<NegBackward>)
tensor(0.0558, grad_fn=<NegBackward>)
tensor(0.0556, grad_fn=<NegBackward>)
tensor(0.055

tensor(0.0305, grad_fn=<NegBackward>)
tensor(0.0305, grad_fn=<NegBackward>)
tensor(0.0305, grad_fn=<NegBackward>)
tensor(0.0304, grad_fn=<NegBackward>)
tensor(0.0304, grad_fn=<NegBackward>)
tensor(0.0303, grad_fn=<NegBackward>)
tensor(0.0303, grad_fn=<NegBackward>)
tensor(0.0302, grad_fn=<NegBackward>)
tensor(0.0302, grad_fn=<NegBackward>)
tensor(0.0302, grad_fn=<NegBackward>)
tensor(0.0301, grad_fn=<NegBackward>)
tensor(0.0301, grad_fn=<NegBackward>)
tensor(0.0300, grad_fn=<NegBackward>)
tensor(0.0300, grad_fn=<NegBackward>)
tensor(0.0299, grad_fn=<NegBackward>)
tensor(0.0299, grad_fn=<NegBackward>)
tensor(0.0299, grad_fn=<NegBackward>)
tensor(0.0298, grad_fn=<NegBackward>)
tensor(0.0298, grad_fn=<NegBackward>)
tensor(0.0297, grad_fn=<NegBackward>)
tensor(0.0297, grad_fn=<NegBackward>)
tensor(0.0296, grad_fn=<NegBackward>)
tensor(0.0296, grad_fn=<NegBackward>)
tensor(0.0296, grad_fn=<NegBackward>)
tensor(0.0295, grad_fn=<NegBackward>)
tensor(0.0295, grad_fn=<NegBackward>)
tensor(0.029

tensor(0.0208, grad_fn=<NegBackward>)
tensor(0.0208, grad_fn=<NegBackward>)
tensor(0.0208, grad_fn=<NegBackward>)
tensor(0.0207, grad_fn=<NegBackward>)
tensor(0.0207, grad_fn=<NegBackward>)
tensor(0.0207, grad_fn=<NegBackward>)
tensor(0.0207, grad_fn=<NegBackward>)
tensor(0.0207, grad_fn=<NegBackward>)
tensor(0.0206, grad_fn=<NegBackward>)
tensor(0.0206, grad_fn=<NegBackward>)
tensor(0.0206, grad_fn=<NegBackward>)
tensor(0.0206, grad_fn=<NegBackward>)
tensor(0.0206, grad_fn=<NegBackward>)
tensor(0.0205, grad_fn=<NegBackward>)
tensor(0.0205, grad_fn=<NegBackward>)
tensor(0.0205, grad_fn=<NegBackward>)
tensor(0.0205, grad_fn=<NegBackward>)
tensor(0.0205, grad_fn=<NegBackward>)
tensor(0.0204, grad_fn=<NegBackward>)
tensor(0.0204, grad_fn=<NegBackward>)
tensor(0.0204, grad_fn=<NegBackward>)
tensor(0.0204, grad_fn=<NegBackward>)
tensor(0.0204, grad_fn=<NegBackward>)
tensor(0.0203, grad_fn=<NegBackward>)
tensor(0.0203, grad_fn=<NegBackward>)
tensor(0.0203, grad_fn=<NegBackward>)
tensor(0.020

In [5]:
print(W,b)
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[3.2715],
        [1.5279]], requires_grad=True) tensor([-14.5674], requires_grad=True)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])
